using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.ChangeTracking;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
using UrgentCareData.Models;

namespace UrgentCareData
{
    public partial class UrgentCareContext : DbContext
    {
        public int SaveChangesWithAudit(string currentUser, bool acceptAllChangesOnSuccess)
        {
            var auditEntries = OnBeforeSaveChanges(currentUser);
            var result = base.SaveChanges(acceptAllChangesOnSuccess);
            OnAfterSaveChanges(auditEntries);
            return result;
        }
        public async Task<int> SaveChangesAsyncWithAudit(string currentUser, CancellationToken cancellationToken = default(CancellationToken))
        {

            var auditEntries = OnBeforeSaveChanges(currentUser);
            var result = await base.SaveChangesAsync(cancellationToken);
            await OnAfterSaveChanges(auditEntries);
            return result;

        }

        private List<AuditEntry> OnBeforeSaveChanges(string currentUser)
        {
            ChangeTracker.DetectChanges();
            var auditEntries = new List<AuditEntry>();
            foreach (var entry in ChangeTracker.Entries())
            {
                if (entry.Entity is Audit || entry.State == EntityState.Detached || entry.State == EntityState.Unchanged || entry.State == EntityState.Added || entry.State == EntityState.Deleted)
                    continue;

                var auditEntry = new AuditEntry(entry, currentUser)
                {
                    TableName = entry.Metadata.GetTableName()
                };
                auditEntries.Add(auditEntry);

                foreach (var property in entry.Properties)
                {
                    if (property.IsTemporary)
                    {
                        // value will be generated by the database, get the value after saving
                        auditEntry.TemporaryProperties.Add(property);
                        continue;
                    }

                    string propertyName = property.Metadata.Name;
                    if (property.Metadata.IsPrimaryKey())
                    {
                        auditEntry.KeyValues[propertyName] = property.CurrentValue;
                        continue;
                    }

                    switch (entry.State)
                    {
                        case EntityState.Added:
                            if (auditEntry.NewValues.GetType() != typeof(byte[]))
                            {
                                auditEntry.NewValues[propertyName] = property.CurrentValue;
                            }

                            break;
                        case EntityState.Deleted:
                            if (auditEntry.NewValues.GetType() != typeof(byte[]))
                            {
                                auditEntry.OldValues[propertyName] = property.OriginalValue;
                            }
                            break;

                        case EntityState.Modified:
                            if (property.IsModified && auditEntry.NewValues.GetType() != typeof(byte[]))
                            {
                                auditEntry.OldValues[propertyName] = property.OriginalValue;
                                auditEntry.NewValues[propertyName] = property.CurrentValue;
                            }
                            break;
                    }
                }
            }

            // Save audit entities that have all the modifications
            foreach (var auditEntry in auditEntries.Where(_ => !_.HasTemporaryProperties))
            {
                Audit.Add(auditEntry.ToAudit());
            }

            // keep a list of entries where the value of some properties are unknown at this step
            return auditEntries.Where(_ => _.HasTemporaryProperties).ToList();
        }

        private Task OnAfterSaveChanges(List<AuditEntry> auditEntries)
        {
            if (auditEntries == null || auditEntries.Count == 0)
            {
                return Task.CompletedTask;
            }

            foreach (var auditEntry in auditEntries)
            {
                // Get the final value of the temporary properties
                foreach (var prop in auditEntry.TemporaryProperties)
                {
                    if (prop.Metadata.IsPrimaryKey())
                    {
                        auditEntry.KeyValues[prop.Metadata.Name] = prop.CurrentValue;
                    }
                    else
                    {
                        auditEntry.NewValues[prop.Metadata.Name] = prop.CurrentValue;
                    }
                }

                // Save the Audit entry
                Audit.Add(auditEntry.ToAudit());
            }

            return SaveChangesAsync();
        }
    }


    public class AuditEntry
    {
        public AuditEntry(EntityEntry entry, string currentUser)
        {
            Entry = entry;
            CurrentUser = currentUser;
        }

        public EntityEntry Entry { get; }
        public string TableName { get; set; }
        public Dictionary<string, object> KeyValues { get; } = new Dictionary<string, object>();
        public Dictionary<string, object> OldValues { get; } = new Dictionary<string, object>();
        public Dictionary<string, object> NewValues { get; } = new Dictionary<string, object>();
        public List<PropertyEntry> TemporaryProperties { get; } = new List<PropertyEntry>();

        public bool HasTemporaryProperties => TemporaryProperties.Any();

        public string CurrentUser { get; set; }
        public Audit ToAudit()
        {
            var audit = new Audit
            {
                TableName = TableName,
                ModifiedBy = CurrentUser,
                ModifiedTime = DateTime.UtcNow,
                KeyValues = JsonConvert.SerializeObject(KeyValues),
                OldValues = OldValues.Count == 0 ? null : JsonConvert.SerializeObject(OldValues),
                NewValues = NewValues.Count == 0 ? null : JsonConvert.SerializeObject(NewValues)
            };
            return audit;
        }
    }
}
