//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.6.1055.0.
// 

namespace PracticeVelocityDomain.DTOs.UpdateChanges
{

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
    public partial class Payer
    {

        private string short_nameField;

        private string payer_numField;

        private string classField;

        private string typeField;

        private string priorityField;

        private string ins_NameField;

        private string ins_Address1Field;

        private string ins_Address2Field;

        private string ins_CityField;

        private string ins_StateField;

        private string ins_ZipField;

        private string ins_RelationshipField;

        private string prim_NameField;

        private string prim_Address1Field;

        private string prim_Address2Field;

        private string prim_CityField;

        private string prim_StateField;

        private string prim_ZipField;

        private string prim_PhoneField;

        private string group_IDField;

        private string member_IDField;

        private string relationshipField;

        private string nameField;

        private string address1Field;

        private string address2Field;

        private string cityField;

        private string stateField;

        private string zipField;

        private string phoneField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string short_name
        {
            get { return this.short_nameField; }
            set { this.short_nameField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string payer_num
        {
            get { return this.payer_numField; }
            set { this.payer_numField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @class
        {
            get { return this.classField; }
            set { this.classField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string type
        {
            get { return this.typeField; }
            set { this.typeField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Priority
        {
            get { return this.priorityField; }
            set { this.priorityField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Ins_Name
        {
            get { return this.ins_NameField; }
            set { this.ins_NameField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Ins_Address1
        {
            get { return this.ins_Address1Field; }
            set { this.ins_Address1Field = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Ins_Address2
        {
            get { return this.ins_Address2Field; }
            set { this.ins_Address2Field = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Ins_City
        {
            get { return this.ins_CityField; }
            set { this.ins_CityField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Ins_State
        {
            get { return this.ins_StateField; }
            set { this.ins_StateField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Ins_Zip
        {
            get { return this.ins_ZipField; }
            set { this.ins_ZipField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Ins_Relationship
        {
            get { return this.ins_RelationshipField; }
            set { this.ins_RelationshipField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Prim_Name
        {
            get { return this.prim_NameField; }
            set { this.prim_NameField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Prim_Address1
        {
            get { return this.prim_Address1Field; }
            set { this.prim_Address1Field = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Prim_Address2
        {
            get { return this.prim_Address2Field; }
            set { this.prim_Address2Field = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Prim_City
        {
            get { return this.prim_CityField; }
            set { this.prim_CityField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Prim_State
        {
            get { return this.prim_StateField; }
            set { this.prim_StateField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Prim_Zip
        {
            get { return this.prim_ZipField; }
            set { this.prim_ZipField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Prim_Phone
        {
            get { return this.prim_PhoneField; }
            set { this.prim_PhoneField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Group_ID
        {
            get { return this.group_IDField; }
            set { this.group_IDField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Member_ID
        {
            get { return this.member_IDField; }
            set { this.member_IDField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Relationship
        {
            get { return this.relationshipField; }
            set { this.relationshipField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Name
        {
            get { return this.nameField; }
            set { this.nameField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Address1
        {
            get { return this.address1Field; }
            set { this.address1Field = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Address2
        {
            get { return this.address2Field; }
            set { this.address2Field = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string City
        {
            get { return this.cityField; }
            set { this.cityField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string State
        {
            get { return this.stateField; }
            set { this.stateField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Zip
        {
            get { return this.zipField; }
            set { this.zipField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Phone
        {
            get { return this.phoneField; }
            set { this.phoneField = value; }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
    public partial class PatientDocuments
    {

        private string fileNameField;

        private string fileTypeField;

        private string numberOfPagesField;

        private string lastVerifiedByField;

        private string lastVerifiedOnField;

        private PatientDocuments[] patientDocuments1Field;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string FileName
        {
            get { return this.fileNameField; }
            set { this.fileNameField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string FileType
        {
            get { return this.fileTypeField; }
            set { this.fileTypeField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string NumberOfPages
        {
            get { return this.numberOfPagesField; }
            set { this.numberOfPagesField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string LastVerifiedBy
        {
            get { return this.lastVerifiedByField; }
            set { this.lastVerifiedByField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string LastVerifiedOn
        {
            get { return this.lastVerifiedOnField; }
            set { this.lastVerifiedOnField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("PvPatientDocument")]
        public PatientDocuments[] PatientDocuments1
        {
            get { return this.patientDocuments1Field; }
            set { this.patientDocuments1Field = value; }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
    public partial class root
    {

        private object[] itemsField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Log_Record", typeof(rootLog_Record),
            Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlElementAttribute("PvPatientDocument", typeof(PatientDocuments))]
        [System.Xml.Serialization.XmlElementAttribute("Payer", typeof(Payer))]
        public object[] Items
        {
            get { return this.itemsField; }
            set { this.itemsField = value; }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class rootLog_Record
    {

        private rootLog_RecordPatient_Information[] patient_InformationField;

        private string svc_dateField;

        private string clinicField;

        private string log_NumField;

        private string last_Upd_UserIDField;

        private string last_Upd_DateTimeField;

        private string diag_CodesField;

        private string diag_Codes_icd10Field;

        private string visitTypeField;

        private string eM_codeField;

        private string physican_IDField;

        private string physicanField;

        private string copay_AmtField;

        private string copay_TypeField;

        private string copay_NotesField;

        private string prev_Pay_AmtField;

        private string prev_Pay_TypeField;

        private string prev_Pay_NotesField;

        private string curr_Pay_AmtField;

        private string curr_Pay_TypeField;

        private string curr_Pay_NotesField;

        private string time_InField;

        private string time_outField;

        private string notesField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Patient_Information",
            Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public rootLog_RecordPatient_Information[] Patient_Information
        {
            get { return this.patient_InformationField; }
            set { this.patient_InformationField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string svc_date
        {
            get { return this.svc_dateField; }
            set { this.svc_dateField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Clinic
        {
            get { return this.clinicField; }
            set { this.clinicField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Log_Num
        {
            get { return this.log_NumField; }
            set { this.log_NumField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Last_Upd_UserID
        {
            get { return this.last_Upd_UserIDField; }
            set { this.last_Upd_UserIDField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Last_Upd_DateTime
        {
            get { return this.last_Upd_DateTimeField; }
            set { this.last_Upd_DateTimeField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Diag_Codes
        {
            get { return this.diag_CodesField; }
            set { this.diag_CodesField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Diag_Codes_icd10
        {
            get { return this.diag_Codes_icd10Field; }
            set { this.diag_Codes_icd10Field = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string visitType
        {
            get { return this.visitTypeField; }
            set { this.visitTypeField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string EM_code
        {
            get { return this.eM_codeField; }
            set { this.eM_codeField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Physican_ID
        {
            get { return this.physican_IDField; }
            set { this.physican_IDField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Physican
        {
            get { return this.physicanField; }
            set { this.physicanField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Copay_Amt
        {
            get { return this.copay_AmtField; }
            set { this.copay_AmtField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Copay_Type
        {
            get { return this.copay_TypeField; }
            set { this.copay_TypeField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Copay_Notes
        {
            get { return this.copay_NotesField; }
            set { this.copay_NotesField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Prev_Pay_Amt
        {
            get { return this.prev_Pay_AmtField; }
            set { this.prev_Pay_AmtField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Prev_Pay_Type
        {
            get { return this.prev_Pay_TypeField; }
            set { this.prev_Pay_TypeField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Prev_Pay_Notes
        {
            get { return this.prev_Pay_NotesField; }
            set { this.prev_Pay_NotesField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Curr_Pay_Amt
        {
            get { return this.curr_Pay_AmtField; }
            set { this.curr_Pay_AmtField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Curr_Pay_Type
        {
            get { return this.curr_Pay_TypeField; }
            set { this.curr_Pay_TypeField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Curr_Pay_Notes
        {
            get { return this.curr_Pay_NotesField; }
            set { this.curr_Pay_NotesField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Time_In
        {
            get { return this.time_InField; }
            set { this.time_InField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Time_out
        {
            get { return this.time_outField; }
            set { this.time_outField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Notes
        {
            get { return this.notesField; }
            set { this.notesField = value; }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class rootLog_RecordPatient_Information
    {

        private Payer[][] payerInformationField;

        private Payer[][] guarantorInformationField;

        private PatientDocuments[] patientDocumentsField;

        private rootLog_RecordPatient_InformationMedicalRecordChart[][] medicalRecordField;

        private string pat_NUMField;

        private string sSNField;

        private string first_NameField;

        private string last_NameField;

        private string middle_NameField;

        private string address1Field;

        private string address2Field;

        private string cityField;

        private string stateField;

        private string zipField;

        private string birthdayField;

        private string sexField;

        private string pat_PhoneField;

        private string proc_codesField;

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("Payer", typeof(Payer), IsNullable = false)]
        public Payer[][] payerInformation
        {
            get { return this.payerInformationField; }
            set { this.payerInformationField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("Payer", typeof(Payer), IsNullable = false)]
        public Payer[][] GuarantorInformation
        {
            get { return this.guarantorInformationField; }
            set { this.guarantorInformationField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("PvPatientDocument")]
        public PatientDocuments[] PatientDocuments
        {
            get { return this.patientDocumentsField; }
            set { this.patientDocumentsField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("Chart",
            typeof(rootLog_RecordPatient_InformationMedicalRecordChart),
            Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = false)]
        public rootLog_RecordPatient_InformationMedicalRecordChart[][] MedicalRecord
        {
            get { return this.medicalRecordField; }
            set { this.medicalRecordField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Pat_NUM
        {
            get { return this.pat_NUMField; }
            set { this.pat_NUMField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string SSN
        {
            get { return this.sSNField; }
            set { this.sSNField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string First_Name
        {
            get { return this.first_NameField; }
            set { this.first_NameField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Last_Name
        {
            get { return this.last_NameField; }
            set { this.last_NameField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Middle_Name
        {
            get { return this.middle_NameField; }
            set { this.middle_NameField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Address1
        {
            get { return this.address1Field; }
            set { this.address1Field = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Address2
        {
            get { return this.address2Field; }
            set { this.address2Field = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string City
        {
            get { return this.cityField; }
            set { this.cityField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string State
        {
            get { return this.stateField; }
            set { this.stateField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Zip
        {
            get { return this.zipField; }
            set { this.zipField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Birthday
        {
            get { return this.birthdayField; }
            set { this.birthdayField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Sex
        {
            get { return this.sexField; }
            set { this.sexField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Pat_Phone
        {
            get { return this.pat_PhoneField; }
            set { this.pat_PhoneField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string proc_codes
        {
            get { return this.proc_codesField; }
            set { this.proc_codesField = value; }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class rootLog_RecordPatient_InformationMedicalRecordChart
    {

        private string dischargedDateField;

        private string dischargedByField;

        private string signOffSealedDateField;

        private string signedOffSealedByField;

        private rootLog_RecordPatient_InformationMedicalRecordChartChartDocument[] chartDocumentField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string DischargedDate
        {
            get { return this.dischargedDateField; }
            set { this.dischargedDateField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string DischargedBy
        {
            get { return this.dischargedByField; }
            set { this.dischargedByField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string SignOffSealedDate
        {
            get { return this.signOffSealedDateField; }
            set { this.signOffSealedDateField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string SignedOffSealedBy
        {
            get { return this.signedOffSealedByField; }
            set { this.signedOffSealedByField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("PvChartDocument",
            Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public rootLog_RecordPatient_InformationMedicalRecordChartChartDocument[] ChartDocument
        {
            get { return this.chartDocumentField; }
            set { this.chartDocumentField = value; }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class rootLog_RecordPatient_InformationMedicalRecordChartChartDocument
    {

        private string fileNameField;

        private string fileTypeField;

        private string numberOfPagesField;

        private string lastUpdatedOnField;

        private string lastUpdatedByField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string FileName
        {
            get { return this.fileNameField; }
            set { this.fileNameField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string FileType
        {
            get { return this.fileTypeField; }
            set { this.fileTypeField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string NumberOfPages
        {
            get { return this.numberOfPagesField; }
            set { this.numberOfPagesField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string LastUpdatedOn
        {
            get { return this.lastUpdatedOnField; }
            set { this.lastUpdatedOnField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string LastUpdatedBy
        {
            get { return this.lastUpdatedByField; }
            set { this.lastUpdatedByField = value; }
        }
    }
}